export default Object.freeze({
  HOME: "Home",
  LOGIN: "Login",
  SIGNUP: "Signup",
  RECYCLE_REQUEST: "RecycleRequest",
  MY_RECYCLE_DETAILS: "MyRecycleDetails",
  ALL_REWARDS: "AllRewards",
  MY_REWARDS: "MyRewards",
  MY_VOUCHER: "MyVoucher",
  RECYCLE_STEPS: "RecycleSteps",
  POINT: "Point",
  TERMS_AND_CONDITIONS: "TermsAndConditions",
  ABOUT_US: "AboutUs",
  MY_POINTS: "MyPoints",
  WITHDRAW: "Withdraw",
  TRANSFER_POINTS: "TransferPoints",
  REMINDER: "Reminder",
  MORE: "More",
  APP_NAVIGATOR: "AppNavigator",
  POINT_MODAL: "PointModal",
  CHANGE_PASSWORD: "ChangePassword",
});
